name: ai_engine_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - pip
  - fastapi
  - uvicorn
  - pip:
      - langchain
      - langchain-pinecone
      - langchain-community
      - langchain-text-splitters
      - langchain-huggingface
      - langchain-openai
      - langchain-groq
      - pinecone-client
      - python-multipart
      - python-dotenv
      - pypdf
      - sentence-transformers