"""retype cv.id to uuid

Revision ID: 587590a06f93
Revises: ebc84dbea308
Create Date: 2026-03-05 12:13:26.075310

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "587590a06f93"
down_revision: Union[str, Sequence[str], None] = "ebc84dbea308"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cv_embeddings",
        "cv_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        postgresql_using="cv_id::uuid",
        existing_nullable=False,
    )
    op.alter_column(
        "cv_profiles",
        "cv_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        postgresql_using="cv_id::uuid",
        existing_nullable=False,
    )
    op.alter_column(
        "cvs",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cvs",
        "id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "cv_profiles",
        "cv_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "cv_embeddings",
        "cv_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
