"""update cv profile

Revision ID: 9cd2c905dd38
Revises: 99f973da980c
Create Date: 2026-03-08 10:51:34.953019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd2c905dd38'
down_revision: Union[str, Sequence[str], None] = '99f973da980c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_profiles', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('cv_profiles', 'cv_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'cv_profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cv_profiles', type_='foreignkey')
    op.alter_column('cv_profiles', 'cv_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('cv_profiles', 'user_id')
    # ### end Alembic commands ###
