"""fix foreign key cv.id column

Revision ID: b2d7ee86d52c
Revises: 587590a06f93
Create Date: 2026-03-05 12:44:14.595260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d7ee86d52c'
down_revision: Union[str, Sequence[str], None] = '587590a06f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cv_embeddings', 'cv_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               postgresql_using="cv_id::uuid",
               existing_nullable=False)
    op.alter_column('cv_profiles', 'cv_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               postgresql_using="cv_id::uuid",
               existing_nullable=False)
    op.alter_column('cvs', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               postgresql_using="cv_id::uuid",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cvs', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cv_profiles', 'cv_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cv_embeddings', 'cv_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
