"""update tables

Revision ID: ee6e0d88f47a
Revises: f113dbb86c52
Create Date: 2026-03-06 16:04:17.163438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6e0d88f47a'
down_revision: Union[str, Sequence[str], None] = 'f113dbb86c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_embeddings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('cv_embeddings', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('cv_embeddings', sa.Column('vector_id', sa.String(), nullable=False))
    op.add_column('cv_embeddings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_cv_embeddings_cv_id'), 'cv_embeddings', ['cv_id'], unique=False)
    op.create_index(op.f('ix_cv_embeddings_user_id'), 'cv_embeddings', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'cv_embeddings', ['vector_id'])
    op.create_foreign_key(None, 'cv_embeddings', 'users', ['user_id'], ['id'])
    op.drop_column('cv_embeddings', 'pinecone_id')
    op.add_column('cv_profiles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cvs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('cvs', 'deleted_at')
    op.drop_column('cv_profiles', 'deleted_at')
    op.add_column('cv_embeddings', sa.Column('pinecone_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cv_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'cv_embeddings', type_='unique')
    op.drop_index(op.f('ix_cv_embeddings_user_id'), table_name='cv_embeddings')
    op.drop_index(op.f('ix_cv_embeddings_cv_id'), table_name='cv_embeddings')
    op.drop_column('cv_embeddings', 'deleted_at')
    op.drop_column('cv_embeddings', 'vector_id')
    op.drop_column('cv_embeddings', 'content')
    op.drop_column('cv_embeddings', 'user_id')
    # ### end Alembic commands ###
