import { Form, useNavigation } from "react-router";
import type { Route } from "./+types/analyze"; // Auto-generated by RR7
import type { AINudgeResponse } from "~/types/ai";
import {
  MessageSquare,
  Send,
  Sparkles,
  Clipboard as ClipboardIcon,
  CheckCircle,
} from "lucide-react";
import { useState } from "react";

const API_URL = `${import.meta.env.VITE_AI_API_URL}/agent/process`;

// Handles the AI Processing
export async function action({ request }: Route.ActionArgs) {
  const formData = await request.formData();
  const jobDescription = formData.get("job_description");

  const response = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ job_description: jobDescription }),
  });

  return (await response.json()) as AINudgeResponse;
}

export default function AIAnalyze({ actionData }: Route.ComponentProps) {
  const navigation = useNavigation();
  const isAnalyzing = navigation.state === "submitting";
  const result = actionData?.data;

  const [copied, setCopied] = useState(false);

  const handleCopy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);

      // Reset the icon after 2 seconds
      setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch (err) {
      console.error("Failed to copy text: ", err);
    }
  };

  return (
    <div className="flex flex-col lg:flex-row h-screen w-full bg-white overflow-hidden">
      {/* COLUMN 1: INPUT AREA (Fixed width on desktop, scrollable) */}
      <div className="w-full lg:w-[450px] border-r border-gray-100 flex flex-col p-6 lg:p-8 bg-white shrink-0 overflow-y-auto">
        <header className="mb-6">
          <h1 className="text-2xl font-black text-gray-900 tracking-tight italic">
            AI Coach
          </h1>
          <p className="text-sm text-gray-500">
            Paste a job description to generate your strategy.
          </p>
        </header>

        <Form method="post" className="flex-1 flex flex-col gap-4">
          <textarea
            name="job_description"
            className="flex-1 min-h-[200px] w-full p-5 bg-gray-50 text-gray-900 border border-gray-100 rounded-2xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all text-sm leading-relaxed placeholder:text-gray-400"
            placeholder="Drop the job requirements here..."
            required
          />
          <button
            type="submit"
            disabled={isAnalyzing}
            className="w-full py-4 bg-blue-600 text-white rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-blue-700 active:scale-[0.98] transition-all shadow-lg shadow-blue-200 shrink-0"
          >
            {isAnalyzing ? (
              <span className="animate-pulse flex items-center gap-2">
                <Sparkles size={18} className="animate-spin" /> Analyzing...
              </span>
            ) : (
              <>
                <Send size={16} /> Generate Strategy
              </>
            )}
          </button>
        </Form>
      </div>

      {/* COLUMN 2: THE STRATEGY PANEL (Responsive and Screen-Fitting) */}
      <div className="flex-1 bg-gray-50/50 flex flex-col overflow-hidden h-full">
        {result ? (
          <div className="flex-1 flex flex-col p-6 lg:p-10 space-y-6 overflow-y-auto">
            {/* MATCH RATING & REASONING (Flexible height, no overflow) */}
            <div className="shrink-0 space-y-6">
              <section>
                <h3 className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-2">
                  Match Rating
                </h3>
                <div className="flex items-baseline gap-2">
                  <span className="text-6xl font-black text-blue-600">
                    {result.match_score}
                  </span>
                  <span className="text-gray-300 text-2xl">/ 10</span>
                </div>
              </section>

              <section className="max-w-2xl">
                <h3 className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-3">
                  Strategic Reasoning
                </h3>
                <div className="border-l-4 border-gray-200 pl-5">
                  <p className="text-gray-700 leading-relaxed italic text-sm md:text-base">
                    "{result.reasoning}"
                  </p>
                </div>
              </section>
            </div>

            {/* THE NUDGE (Actionable Output - Optimized to fit screen) */}
            <section className="flex-1 min-h-[300px] flex flex-col max-w-3xl">
              <div className="flex-1 bg-[#1a1d23] text-white p-6 md:p-8 rounded-[2rem] shadow-2xl relative overflow-hidden flex flex-col border border-white/5">
                {/* Card Header */}
                <div className="flex justify-between items-center mb-6 shrink-0">
                  <div className="flex items-center gap-2">
                    <div className="p-2 bg-blue-500/20 rounded-lg text-blue-400">
                      <MessageSquare size={18} />
                    </div>
                    <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-400">
                      Suggested LinkedIn Nudge
                    </h3>
                  </div>
                </div>

                {/* SCROLLABLE CONTENT WITHIN THE CARD */}
                <div className="flex-1 overflow-y-auto pr-2 mb-6 custom-scrollbar">
                  <p className="text-base md:text-lg font-medium leading-relaxed text-gray-100">
                    {result.nudge}
                  </p>
                </div>

                {/* Action Button */}
                <button
                  onClick={() => handleCopy(result.nudge)}
                  className={`flex items-center justify-center gap-2 px-6 py-4 rounded-2xl text-sm font-black transition-all active:scale-[0.97] shrink-0 w-full ${
                    copied
                      ? "bg-emerald-500 text-white" // Feedback state color
                      : "bg-white text-black hover:bg-gray-100" // Default state color
                  }`}
                >
                  {copied ? (
                    <>
                      <CheckCircle
                        size={16}
                        className="animate-in zoom-in duration-300"
                      />
                      <span>Copied to Clipboard!</span>
                    </>
                  ) : (
                    <>
                      <ClipboardIcon size={16} />
                      <span>Copy to Clipboard</span>
                    </>
                  )}
                </button>

                {/* Decorative Background Glow */}
                <div className="absolute -bottom-20 -right-20 w-64 h-64 bg-blue-600/10 rounded-full blur-[80px] pointer-events-none"></div>
              </div>
            </section>
          </div>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center text-gray-300 text-center p-10">
            <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mb-4">
              <Sparkles
                size={32}
                strokeWidth={1}
                className="opacity-40 text-blue-500"
              />
            </div>
            <h2 className="text-lg font-bold text-gray-400">
              Ready to analyze
            </h2>
            <p className="max-w-xs text-sm mt-2">
              Submit a job description to get your match rating and tailored
              outreach strategy.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
